-- Create favorites table
CREATE TABLE IF NOT EXISTS public.favorites (
    favorite_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    account_id INTEGER NOT NULL,
    inv_id INTEGER NOT NULL,
    favorite_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pk PRIMARY KEY (favorite_id),
    CONSTRAINT fk_account 
        FOREIGN KEY (account_id)
        REFERENCES public.account (account_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_inventory
        FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    -- Prevent duplicate favorites
    CONSTRAINT unique_favorite 
        UNIQUE (account_id, inv_id)
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_favorites_account 
    ON public.favorites(account_id);
CREATE INDEX IF NOT EXISTS idx_favorites_inventory 
    ON public.favorites(inv_id);